# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storekit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='expires_date',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='create_date',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
